apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
    role: downstream
    demo: blast-radius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        role: downstream
    spec:
      containers:
        - name: payment
          image: {{.Values.image}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8002
          env:
            - name: SERVICE_VERSION
              value: "{{.Values.serviceVersion}}"
            - name: PORT
              value: "{{.Values.port}}"
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 192Mi
