apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
    role: downstream
    demo: blast-radius
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
  selector:
    app: payment
