apiVersion: v1
kind: Service
metadata:
  name: blast-radius-sim
  labels:
    app: blast-radius-sim
    demo: blast-radius
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: blast-radius-sim
