apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
    role: downstream
    demo: blast-radius
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
  selector:
    app: notification
