apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app: checkout
    role: main
    demo: blast-radius
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: checkout
